from typing import Protocol, Sequence, Optional
from datetime import datetime
from .entities import ScrapedPost, Query, TwitterUser, Tweet, MediaFile, UserRecentTweet

class ScraperPort(Protocol):
    async def search(self, query: str, limit: int = 20) -> Sequence[ScrapedPost]:
        ...
    
    async def search_tweets(self, query: Query, limit: int = 20) -> Sequence[Tweet]:
        """Enhanced search that returns Tweet entities with full metadata"""
        ...
    
    async def get_user_profile(self, user_id: str) -> Optional[TwitterUser]:
        """Fetch user profile information"""
        ...
    
    async def get_user_recent_tweets(self, user_id: str, count: int = 3) -> Sequence[Tweet]:
        """Get recent tweets from a user"""
        ...

class QueryRepositoryPort(Protocol):
    async def save(self, query: Query) -> Query:
        ...
    async def get_by_id(self, query_id: int) -> Optional[Query]:
        ...
    async def list_active(self) -> list[Query]:
        ...
    async def update_last_run(self, query_id: int, timestamp: datetime) -> None:
        ...
    async def delete(self, query_id: int) -> bool:
        ...

class TwitterUserRepositoryPort(Protocol):
    async def save(self, user: TwitterUser) -> TwitterUser:
        ...
    async def get_by_id(self, user_id: str) -> Optional[TwitterUser]:
        ...
    async def get_by_username(self, username: str) -> Optional[TwitterUser]:
        ...
    async def list_for_auto_update(self) -> list[TwitterUser]:
        ...
    async def update_profile(self, user: TwitterUser) -> TwitterUser:
        ...

class TweetRepositoryPort(Protocol):
    async def save_many(self, tweets: list[Tweet]) -> int:
        ...
    async def get_by_id(self, tweet_id: str) -> Optional[Tweet]:
        ...
    async def list_by_query(self, query_id: int, limit: int = 100) -> list[Tweet]:
        ...
    async def list_recent(self, limit: int = 50) -> list[Tweet]:
        ...
    async def get_duplicates(self, tweet_ids: list[str]) -> set[str]:
        ...

class MediaFileRepositoryPort(Protocol):
    async def save(self, media_file: MediaFile) -> MediaFile:
        ...
    async def get_by_tweet(self, tweet_id: str) -> list[MediaFile]:
        ...
    async def save_many(self, media_files: list[MediaFile]) -> int:
        ...

class UserRecentTweetRepositoryPort(Protocol):
    async def save_user_tweets(self, user_id: str, tweets: list[UserRecentTweet]) -> int:
        ...
    async def get_by_user(self, user_id: str) -> list[UserRecentTweet]:
        ...

# Legacy repository for backward compatibility
class PostRepositoryPort(Protocol):
    async def save_many(self, posts: list[ScrapedPost]) -> int:
        ...
    async def get_by_id(self, post_id: str) -> Optional[ScrapedPost]:
        ...
    async def list_recent(self, limit: int = 50) -> list[ScrapedPost]:
        ...

